name: Somnus Lab - Transmisión Infinita
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Se activa automáticamente cada 6 horas

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Instalar FFmpeg
        run: sudo apt update && sudo apt install -y ffmpeg

      - name: Descargar y Transmitir
        run: |
          # Descarga desde Dropbox (Asegúrate de que termine en dl=1)
          wget -O video.mp4 https://www.dropbox.com/scl/fi/h2mnvx5dw7glso89otaiy/video.mp4?dl=1
          
          # Transmitimos por 6 horas y 5 minutos (21900 segundos)
          # Esto garantiza que la señal nunca se corte antes de que el siguiente ciclo empiece
          ffmpeg -re -stream_loop -1 -i video.mp4 -t 21900 -c:v libx264 -preset veryfast -b:v 2500k -maxrate 2500k -bufsize 5000k -pix_fmt yuv420p -g 60 -c:a aac -b:a 128k -ar 44100 -f flv rtmp://a.rtmp.youtube.com/live2/${{ secrets.YOUTUBE_KEY }}
